// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/HeroConcepts.tsx": () => import("../components/mockups/HeroConcepts.tsx"),
  "./components/mockups/HeroConcepts/ConceptA.tsx": () => import("../components/mockups/HeroConcepts/ConceptA.tsx"),
  "./components/mockups/HeroConcepts/ConceptB.tsx": () => import("../components/mockups/HeroConcepts/ConceptB.tsx"),
  "./components/mockups/HeroConcepts/ConceptC.tsx": () => import("../components/mockups/HeroConcepts/ConceptC.tsx"),
  "./components/mockups/HeroConcepts/ConceptD.tsx": () => import("../components/mockups/HeroConcepts/ConceptD.tsx"),
  "./components/mockups/HeroConcepts/ConceptE.tsx": () => import("../components/mockups/HeroConcepts/ConceptE.tsx"),
  "./components/mockups/HeroConcepts/ConceptF.tsx": () => import("../components/mockups/HeroConcepts/ConceptF.tsx")
};
